# Generated by Django 4.1.7 on 2023-03-19 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gifti", "0002_wish_nametag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="nametag",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nametag",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
